spring:
  datasource:
    url: jdbc:h2:mem:tests
    driver_class_name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
logging:
  level:
    org.avaje.ebean:
      SQL: DEBUG
      TXN: DEBUG
