spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver_class_name: org.postgresql.Driver
    username: postgres
    password: postgres
logging:
  level:
    org.avaje.ebean:
      SQL: DEBUG
      TXN: DEBUG
